### ISSUE TITLE
Error: invalid operation; wallet.createDB

### ISSUE THREAD

**Issue by the-wunmi** [raedahgroup/dcrlibwallet#17]
There is a dcrlibwallet error while trying to create a wallet on the decred android mobile app, the attached screenshot describes the error.
![Screenshot_1552921688](https://user-images.githubusercontent.com/12461844/54540506-67646480-4998-11e9-8522-f1f00abf0097.png)

**Comment by C-ollins** [comment]
Can you confirm that this bug still exists? Try building dcrlibwallet master and https://github.com/decred/dcrandroid/pull/291. I just tried that and didn't come across this error.

**Comment by itswisdomagain** [comment]
I believe this can be closed too.
