### ISSUE TITLE
GetTransactions takes ~4 seconds to return transactions

### ISSUE THREAD

**Issue by C-ollins** [raedahgroup/dcrlibwallet#40]
Calling `GetTransactions` takes up ~4 seconds to return ~800 transactions which is quite slow. Tracing down issue shows that all those seconds were spent receiving transactions from dcrwallet which makes dcrwallet the main cause of the issue.
A fix was implemented in https://github.com/raedahgroup/dcrlibwallet/pull/15 The implementation queries transactions from dcrwallet and saves it in storm db which is managed directly from dcrlibwallet. This makes it faster to query transactions and also allows us to query transactions based on attributes.

**Comment by itswisdomagain** [comment]
This can be closed now @C-ollins.
